# Generated by Django 5.2.6 on 2026-02-21 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='selected_body_parts',
            field=models.ManyToManyField(blank=True, to='symptoms.bodypart'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitalclinicprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctorprofile'),
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='accounts.hospitalclinicprofile'),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='accounts.specialization'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='accounts.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doctorworkinghours',
            unique_together={('doctor', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='hospitaldoctors',
            unique_together={('hospital', 'doctor')},
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['is_available', 'experience'], name='accounts_do_is_avai_ef9b4b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorprofile',
            index=models.Index(fields=['rating_avg', 'num_reviews'], name='accounts_do_rating__c8944f_idx'),
        ),
    ]
