# Generated by Django 5.2.6 on 2026-02-21 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(help_text='Date of the appointment')),
                ('patient_message', models.TextField(blank=True, help_text="Patient's description of the issue or reason for appointment")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10)),
                ('doctor_provided_time', models.TimeField(blank=True, help_text='Approximate visit time provided by doctor upon acceptance', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason provided by doctor for rejection')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason provided by patient for cancellation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.patientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['doctor', 'status'], name='accounts_ap_doctor__4e8746_idx'), models.Index(fields=['patient', 'status'], name='accounts_ap_patient_16454f_idx'), models.Index(fields=['appointment_date'], name='accounts_ap_appoint_8d29f0_idx')],
            },
        ),
    ]
