# Generated by Django 5.2.6 on 2026-03-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, help_text='Hospital for appointment (for hospital bookings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.hospitalclinicprofile'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, help_text='Doctor for appointment (for doctor bookings)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.doctorprofile'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status'], name='accounts_ap_hospita_0f9eef_idx'),
        ),
    ]
