# Generated by Django 5.2.6 on 2026-03-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appointment_hospital_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalclinicprofile',
            name='availability_last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last time availability was toggled'),
        ),
        migrations.AddField(
            model_name='hospitalclinicprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Hospital is open for appointments'),
        ),
        migrations.CreateModel(
            name='HospitalWorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField(blank=True, help_text='Leave blank if day is off', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Leave blank if day is off', null=True)),
                ('is_off', models.BooleanField(default=False, help_text='Check if hospital is closed on this day')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='accounts.hospitalclinicprofile')),
            ],
            options={
                'unique_together': {('hospital', 'day_of_week')},
            },
        ),
    ]
