# Generated by Django 5.2.6 on 2026-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospitalclinicprofile_availability_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Admin activates after payment verification'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_message',
            field=models.TextField(blank=True, help_text='Message from user during payment submission'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='subscriptions/payments/'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When admin verified the payment', null=True),
        ),
    ]
