# Generated by Django 5.2.6 on 2026-03-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usersubscription_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('co_founder', 'Co-Founder'), ('developer', 'Developer'), ('designer', 'Designer'), ('doctor_advisor', 'Doctor / Medical Advisor'), ('data_scientist', 'Data Scientist'), ('marketing', 'Marketing'), ('support', 'Support'), ('other', 'Other')], default='other', max_length=30)),
                ('custom_role_label', models.CharField(blank=True, help_text='Override display role label (optional)', max_length=100)),
                ('short_bio', models.TextField(blank=True, help_text='Short bio shown on the homepage card', max_length=300)),
                ('photo', models.ImageField(blank=True, help_text='Team member photo (recommended 400x400px)', null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order on homepage (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
