# Generated by Django 5.2.6 on 2026-02-21 14:44

import blog.models
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('tags', models.CharField(help_text='Comma separated tags', max_length=500)),
                ('content_intro', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Introduction')),
                ('content_section1', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Section 1')),
                ('content_section2', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Section 2')),
                ('content_conclusion', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Conclusion')),
                ('thumbnail', models.ImageField(help_text='Thumbnail image (800x400px)', upload_to='blog/thumbnails/', validators=[blog.models.ValidateImageDimensions(height=400, width=800)])),
                ('image1', models.ImageField(help_text='Additional image 1 (1200x600px)', upload_to='blog/images/', validators=[blog.models.ValidateImageDimensions(height=600, width=1200)])),
                ('image2', models.ImageField(help_text='Additional image 2 (1200x600px)', upload_to='blog/images/', validators=[blog.models.ValidateImageDimensions(height=600, width=1200)])),
                ('image3', models.ImageField(help_text='Additional image 3 (1200x600px)', upload_to='blog/images/', validators=[blog.models.ValidateImageDimensions(height=600, width=1200)])),
                ('creator_email', models.EmailField(max_length=254)),
                ('creator_phone', models.CharField(blank=True, max_length=15)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_deleted', 'created_at'], name='blog_blog_is_dele_189215_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('blog', 'user')},
        ),
    ]
