# Generated by Django 5.2.6 on 2026-02-21 14:44

import django.core.validators
import django.db.models.deletion
import symptoms.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.FileField(blank=True, null=True, upload_to='body_parts/icons/', validators=[symptoms.models.validate_icon_file])),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('common_causes', models.TextField(blank=True)),
                ('prevention_tips', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('treatment_advice', models.TextField(blank=True)),
                ('when_to_see_doctor', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('specializations', models.ManyToManyField(blank=True, related_name='illnesses', to='accounts.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('common_causes', models.TextField(blank=True)),
                ('body_parts', models.ManyToManyField(blank=True, related_name='symptoms', to='symptoms.bodypart')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomCheckSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='IllnessSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_severity_weight', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('mid_severity_weight', models.FloatField(default=0.6, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('high_severity_weight', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illness_symptoms', to='symptoms.illness')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
            ],
            options={
                'unique_together': {('illness', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='SymptomCheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('reasoning', models.TextField(blank=True)),
                ('illness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.illness')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='symptoms.symptomchecksession')),
            ],
            options={
                'ordering': ['-probability_score'],
                'unique_together': {('session', 'illness')},
            },
        ),
        migrations.CreateModel(
            name='SelectedSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_severity', models.CharField(choices=[('low', 'Low'), ('mid', 'Medium'), ('high', 'High')], max_length=10)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.symptom')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_symptoms', to='symptoms.symptomchecksession')),
            ],
            options={
                'unique_together': {('session', 'symptom')},
            },
        ),
    ]
