# Generated by Django 5.2.6 on 2026-04-13 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
    ]
