# Generated by Django 5.2.6 on 2026-04-13 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_add_prevalence_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='illness',
            name='prevalence_weight',
            field=models.FloatField(default=0.5, help_text='Weight based on how common this illness is (1.0 = very common, 0.2 = very rare)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
